# Generated by Django 3.1.5 on 2021-01-28 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(upload_to='image/')),
                ('bio', models.CharField(max_length=300)),
                ('username', models.CharField(default='Your username', max_length=50)),
            ],
        ),
    ]
